### ISSUE TITLE
Bug - Reported execution times incorrect, pulling from bytes value instead

### ISSUE THREAD

**Issue by InverseFalcon** [kvegter/query-analyzer-app#14]
Query Log Analyzer 1.0.9
Running from Neo4j Desktop 1.5.7.102
On a 2019 Macbook Pro 

Neo4j 4.3.2 query logs
Timings enabled

We observed that the query log analyzer was showing execution times for average, min, max (but not for the cpu, planning, and waiting times) that were not actually present in the query logs, and on further investigation it seemed to be pulling these numbers from the bytes segment of the query log entry.

Here is one sample entry that can be used to reproduce the issue. IPs, query, and parameters changed, so no sensitive info is exposed:

```
2023-05-01 17:22:01.087+0000 INFO  3527 ms: (planning: 218, cpu: 3501, waiting: 0) - 30330704 B - 3126025 page hits, 0 page faults - bolt-session	bolt	neo4j-java/4.3.2-c88becf4b4c1d99261989ce52dda3bb0481930d2		client/10.10.10.10:20352	server/10.10.10.10:7687>	graph.db - neo4j - RETURN 1 as done - {} - runtime=pipelined - {}
```

A query log file with only this entry, when run through the query log analyzer, showed avg/min/max execution time as 30330704 ms, which is actually the bytes value used by the query.

**Comment by kvegter** [comment]
This is fixed in version 1.0.10
