### ISSUE TITLE
Bug : 3.4/3.5 embedded log entries not parsed correctly

### ISSUE THREAD

**Issue by pecollet** [kvegter/query-analyzer-app#15]
Regression introduced in 1.0.9.
For 3.x query.logs (without query ids), parsing of the "elapsed time" is broken for "embedded" sessions.

Example below.

- query.log contains the following entry:

```
2021-05-13 13:24:58.485+0000 INFO  1290 ms: embedded-session		 - MATCH (a:` This query is just used to load the cypher compiler during warmup. Please ignore `) RETURN a LIMIT 0 - {} - {}
```

- result contains the timestamp's "year" value instead of the elapsed time

![image](https://github.com/kvegter/query-analyzer-app/assets/45878183/4d7452d8-2780-45ea-b590-5cea5bd9a8fa)

=> in [`_parseEmbeddedLine`  ](https://github.com/kvegter/query-analyzer-app/blob/ec4eec2973c0e3e1ba0e09195c12557ce9b19532/lib/qanalyzer.js#L3120), `this._getFieldIndex(field0fields,"-")` returns -1, causing field [0] to be return for `qr.queryMillis`.

**Comment by kvegter** [comment]
Fixed in release 1.0.11
