### ISSUE TITLE
Remote Instance Connection

### ISSUE THREAD

**Issue by bradleygore** [kvegter/query-analyzer-app#2]
I have a neo4j instance running locally, and this app works very nicely. However, when I create a neo4j connection to a remote server, the neo4j Desktop app can connect just fine but this app cannot.

Neo4j Version: 4.1.1 Enterprise
Neo4j Query Log Analyzer version 1.0.1
Remote URL is on port 443 and is using encrypted connection, if that is useful.

I get two separate errors in the query analyzer:
**Query Stats**: `You will need to be connected to a database version of 3.5.4 or higher to have this functionality`
**Current Queries**: `Need connection to database server to use this function`

**Comment by kvegter** [comment]
Hi, the tool uses only bolt to connect to the database, is that port open for you? Anyway point taken for the default messages when you do not have a connection. I am also interested in what the javascript console gives you, only available if you set the neo4j desktop in development mode

**Comment by kvegter** [comment]
Fixed in 1.0.2

**Comment by busymo** [comment]
Trying to connect with the remote db (in the same k8s cluster) with 443. It cannot find the query.log on the neo4j server. Any fix idea?
