### ISSUE TITLE
query-log-analyzer v1.0.3  does not support neo4j 3.6

### ISSUE THREAD

**Issue by slavo3** [kvegter/query-analyzer-app#5]
Hi, new version doesn't support Neo4J 3.6 :(
`Neo4jError: Unknown procedure output: `databases` (line 1, column 47 (offset: 46)) "call dbms.cluster.overview() yield addresses, databases " ^`

Is it possible to install version 1.0.2 using old: link https://neo.jfrog.io/neo/api/npm/npm/query-log-analyzer

I can't afford to update the neo4j version yet and I would like to have a working query-log-analyzer.

**Comment by kvegter** [comment]
Do you really have version 3.6? To my knowledge that version was never there

**Comment by kvegter** [comment]
It is now fixed.
