### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by jasperblues** [kvegter/query-analyzer-app#6]
Very motivated to sue this app to get better statistics on query performance, however: 

* Seems the OAuth login doesn't currently work, returns a 404
* Signing up with a username/password pair to MyJFrog seems broken too. Never received confirmation email.

**Comment by kvegter** [comment]
- Hi OAuth is not supported. I will investigate it.
- Also the package location is changed if you use it from the neo4j desktop, it is now on https://registry.npmjs.org/query-log-analyzer. 
An alternative is also to run the qla via tools.neo4jlabs.com in you webbrowser.

**Comment by kvegter** [comment]
fixed
